export const myProjects = [
  {
    id: 1,
    projectTitle: "React project",
    category: "React",
    imgPath: "./img/exercies.png",
    title:"Fitness-React-App",
    description:"Advanced React Best Practices such as file structure and hooks, Creating a Beautiful User Interface using the Material UI (version 5), Fetching data from unlimited sources using RapidAPI",
    link: "https://github.com/Eslam-Mohamed-G/Fitness-React-App",
    live: "https://fitness-react-app-one.vercel.app/",
  },
  {
    id: 2,
    projectTitle: "HTML&CSS project",
    category: "css",
    imgPath: "./img/Exam_1.png",
    title:"Rout Exam-1",
    description:"In this project, I agreed on an interactive user interface using HTML, CSS, JavaScript and Bootstrap. I focused on a simple, attractive and easy-to-use design, an interface with presence on various devices. Using Bootstrap, I was able to accelerate development and design ready-made applications to participate in the user experience, while using JavaScript functions Interactive ease of use and adds dynamism to the site.",
    live: "https://rout-exam-1.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/Rout-Exam_1",
  },
  {
    id: 3,
    projectTitle: "JavaScript project",
    category: "JS",
    imgPath: "./img/contact.png",
    title:"Contact form",
    description:"Building accessible forms is a crucial task for front-end developers. This challenge will help you practice building a form with several input types and validation.",
    live: "https://contact-form-five-lac.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/contact-form",
  },
  {
    id: 4,
    projectTitle: "HTML & CSS project",
    category: "css",
    imgPath: "./img/four-card.jpg",
    title:"Four card feature section",
    description:"A nice layout-based challenge for beginners. This will test anyone who is new to multi-column and responsive layouts.",
    live: "https://four-card-feature-section-master-roan-nine.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/four-card-feature-section-master",
  },
  {
    id: 5,
    projectTitle: "JavaScript project",
    category: "JS",
    imgPath: "./img/interactive.png",
    title:"Interactive card details form",
    description:"This fun project will be an excellent way to practice DOM manipulation and form validation while also putting your HTML and CSS skills to the test.",
    live: "https://interactive-card-details-form-amber-six.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/interactive-card-details-form",
  },
  {
    id: 6,
    projectTitle: "React project",
    category: "React",
    imgPath: "./img/list.png",
    title:"Todo List App",
    description:"Todo List App, My first React-project, I learn how to use components, state, props, and more to create a fully functional Todo List.",
    live: "https://to-do-list-by-react.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/To_Do_list-by-React",
  },
  {
    id: 7,
    projectTitle: "HTML & CSS project",
    category: "css",
    imgPath: "./img/previewMealify.png",
    title:"Enjoy Your Healthy Delicious Food",
    description:"We will see through this project the power of css. this projects is assignment number 5 from Rout",
    live: "https://rout-mealify5.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/Rout_Mealify5",
  },
  {
    id: 8,
    projectTitle: "JavaScript project",
    category: "JS",
    imgPath: "./img/gamesAPI.png",
    title:"Game over app",
    description:"This project is a web application for exploring free-to-play games, fetching data from the Free-to-Play Games Database API, and displaying it using a responsive design. The app utilizes JavaScript with an object-oriented programming (OOP) approach to ensure maintainable and scalable code.",
    live: "https://game-over-route-rouge.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/Game-over-Route",
  },
  {
    id: 9,
    projectTitle: "React project",
    category: "React",
    imgPath: "./img/dashboard.png",
    title:"React Admin Dashboard",
    description:"React Admin Dashboard. I used React, Material UI, Nivo Charts, Formik, Yup, FullCalendar, and Data Grid to build this entire application. This application consists of Light and Dark Mode, 4 different Charts, 3 different Data Table Pages, FAQ Page, Form Page, and Calendar Integration.",
    live: "https://dashboard-rho-mocha-56.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/Dashboard",
  },
];
