export const myProjects = [
  {
    id: 1,
    projectTitle: "React project",
    category: "React",
    imgPath: "./img/exercies.png",
    title:"Fitness-React-App",
    desription:"Advanced React Best Practices such as file structure and hooks, Creating a Beautiful User Interface using the Material UI (version 5), Fetching data from unlimited sources using RapidAPI",
    link: "https://github.com/Eslam-Mohamed-G/Fitness-React-App",
    live: "https://fitness-react-app-one.vercel.app/",
  },
  {
    id: 2,
    projectTitle: "HTML&CSS project",
    category: "css",
    imgPath: "./img/testimonials.png",
    title:"Testimonials grid section",
    desription:"This challenge will be perfect practice for anyone wanting to test their CSS Grid skills. Grid is such a powerful addition to CSS, so it's worth getting to grips with it!",
    live: "https://testimonials-grid-section-main-three-zeta.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/testimonials-grid-section-main",
  },
  {
    id: 3,
    projectTitle: "JavaScript project",
    category: "JS",
    imgPath: "./img/contact.png",
    title:"Contact form",
    desription:"Building accessible forms is a crucial task for front-end developers. This challenge will help you practice building a form with several input types and validation.",
    live: "https://contact-form-five-lac.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/contact-form",
  },
  {
    id: 4,
    projectTitle: "HTML & CSS project",
    category: "css",
    imgPath: "./img/four-card.jpg",
    title:"Four card feature section",
    desription:"A nice layout-based challenge for beginners. This will test anyone who is new to multi-column and responsive layouts.",
    live: "https://four-card-feature-section-master-roan-nine.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/four-card-feature-section-master",
  },
  {
    id: 5,
    projectTitle: "JavaScript project",
    category: "JS",
    imgPath: "./img/interactive.png",
    title:"Interactive card details form",
    desription:"This fun project will be an excellent way to practice DOM manipulation and form validation while also putting your HTML and CSS skills to the test.",
    live: "https://interactive-card-details-form-amber-six.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/interactive-card-details-form",
  },
  {
    id: 6,
    projectTitle: "React project",
    category: "React",
    imgPath: "./img/list.png",
    title:"Todo List App",
    desription:"Todo List App, My first React-project, I learn how to use components, state, props, and more to create a fully functional Todo List.",
    live: "https://to-do-list-by-react.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/To_Do_list-by-React",
  },
  {
    id: 7,
    projectTitle: "HTML & CSS project",
    category: "css",
    imgPath: "./img/social.png",
    title:"Social links profile",
    desription:"In this small project, you'll build out your social link-sharing profile. You can even personalize it and use it to share all your social profiles!",
    live: "https://social-links-profile-kohl-sigma.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/social-links-profile",
  },
  {
    id: 8,
    projectTitle: "JavaScript project",
    category: "JS",
    imgPath: "./img/age calculater.png",
    title:"Age calculator app",
    desription:"This challenge is designed to sharpen your JavaScript and form validation skills. Working with dates in JavaScript can be tricky, so this will be a nice test!",
    live: "https://age-calculator-app-main-pink.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/age-calculator-app-main",
  },
  {
    id: 9,
    projectTitle: "React project",
    category: "React",
    imgPath: "./img/dashboard.png",
    title:"React Admin Dashboard",
    desription:"React Admin Dashboard. I used React, Material UI, Nivo Charts, Formik, Yup, FullCalendar, and Data Grid to build this entire application. This application consists of Light and Dark Mode, 4 different Charts, 3 different Data Table Pages, FAQ Page, Form Page, and Calendar Integration.",
    live: "https://dashboard-rho-mocha-56.vercel.app/",
    link: "https://github.com/Eslam-Mohamed-G/Dashboard",
  },
];
